(declaim (optimize (speed 3)))

(defun pro29 ()
  (let ((hs (make-hash-table :test #'eql))
	(cnt 0))
    (dotimes (i 99)
      (dotimes (j 99)
	(let ((n (expt (+ i 2) (+ j 2))))
	  (multiple-value-bind (val fnd)
	      (gethash n hs)
	    (when (null fnd)
	      (incf cnt)
	      (setf (gethash n hs) val))))))
    cnt))